name: Test
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request: {}
jobs:
  download:
    name: Testing Download
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: GolangCI-Lint
        id: release_download
        uses: ./github-release-download
        with:
          tool: golangci-lint
          owner: golangci
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_format: $TOOL-$SVERSION-$OS-$ARCH
          has_root_folder: true
      - name: Mesa-CLI
        if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]' # Only run private check for prs from repo not made by dependabot
        uses: ./github-release-download
        with:
          repo: mesa-cli
          tool: mesa
          github_token: ${{ secrets.CI_GITHUB_TOKEN }}
          bin: bin
      - name: Assert Public Release Download
        env:
          RELEASE_PATH: ${{ steps.release_download.outputs.download_path }}
        run: |
          echo $RELEASE_PATH
          golangci-lint --version
      - name: Assert Private Release Download
        if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]' # Only run private check for prs from repo not made by dependabot
        env:
          RELEASE_PATH: ${{ steps.release_download.outputs.download_path }}
        run: |
          echo $RELEASE_PATH
          mesa --version
  environment:
    name: Testing Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set Environment
        uses: ./set-environment-variables
        env:
          RANDOM_ENV: foo
          ANOTHER_VAR: bar
        with:
          variables: RANDOM_ENV,ANOTHER_VAR
      - name: Read Environment
        run: |
          [ "$RANDOM_ENV" = "foo" ]
          [ "$ANOTHER_VAR" = "bar" ]

  terraform:
    name: Testing Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get Terraform
        uses: ./setup-terraform
        with:
          version: v1.3.2
      - name: Assert Terraform on PATH
        run: terraform --version
